apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  containers:
    - name: alpine
      image: alpine
      ports:
        - containerPort: 81
