apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-labels
  labels:
    label-key1: label-value1
    label-key2: label-value2
    label-key3: label-value3
  annotations:
    annotation-key1: annotation-value
    annotation-key1: very long annotation, with many word
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
